### PR TITLE
Debug CI: Remove workspace from `delegator`

### PR DESCRIPTION
**Pull request by cmichi**
Not intended for merge, this is just here to debug the failing CI for https://github.com/paritytech/ink/pull/1054.

### CODE REVIEW

**Comment by xgreenx** [comment]
> ## 🦑 📈 ink! Example Contracts ‒ Size Change Report 📉 🦑
> These are the results of building the `examples/*` contracts from this branch with `cargo-contract 0.16.0`:
> 
> [Link to the run](https://gitlab.parity.io/parity/ink-waterfall/-/pipelines/168372) | Last update: Mon Nov 29 09:44:54 CET 2021

It failed to parse the result=)
image

**Comment by cmichi** [comment]
> > ## squid chart_with_upwards_trend ink! Example Contracts ‒ Size Change Report chart_with_downwards_trend squid
> > These are the results of building the `examples/*` contracts from this branch with `cargo-contract 0.16.0`:
> > [Link to the run](https://gitlab.parity.io/parity/ink-waterfall/-/pipelines/168372) | Last update: Mon Nov 29 09:44:54 CET 2021
> 
> It failed to parse the result=) image

**Comment by xgreenx** [comment]
The change is ready, so I'm waiting for your comments=)

**Comment by xgreenx** [comment]
@cmichi Something is wrong with `Total Optimized Size` in the size report=). It is huge.

**Pull request closed without merging**
