### PR TITLE
Enum spread allocate

### PR DESCRIPTION
**Pull request by forgetso**
This is my attempt to identify when an `enum` has derived `Default` from its representation as a `synstructure` for https://github.com/paritytech/ink/issues/1042.

For exmaple, an `enum` like this would be allowed:
```
#[derive(Default)]
enum Enum { A, B, #[default] C }
```
But this one would fail:
`        enum Enum { A, B, C }`

I don't know how to do this without using the `Default` derive. If you create the default value using `impl`, the `synstructure`, contains no information about the default. Additionally, you cannot pass `impl` into the `synstructure::Structure::new`.

```
    pub enum Enum {
        A,
        B,
        C,
    }

    impl Default for Status {
        fn default() -> Self { Enum::C }
    }

```

### CODE REVIEW

**Comment by forgetso** [comment]
Also, I've been running `rustfmt` on this but it seems to format it differently from your CI `rustfmt`.

**Comment by HCastano** [comment]
@forgetso thanks for the PR! I'm gonna put this `on-ice` since we're still unsure about the direction we want to take with `SpreadAllocate` in general.

**Comment by paritytech-cicd-pr** [comment]
## 🦑 📈 ink! Example Contracts ‒ Changes Report 📉 🦑
 These are the results when building the `examples/*` contracts from this branch with `cargo-contract 0.17.0-86510f8` and comparing them to ink! `master`: 

|                      | Δ Optimized Size | Δ Used Gas | Total Optimized Size | Total Used Gas |
|:----------------------|------------------:|------------:|----------------------:|----------------:|
| `accumulator`        |                  |            | 1.44 K               |                |
| `adder`              |                  |            | 2.94 K               |                |
| `contract-terminate` |                  | +14_926    | 1.31 K               | 215_704        |
| `contract-transfer`  |                  | +14_305    | 7.98 K               | 15_704         |
| `delegator`          |                  | +41_047    | 7.63 K               | 51_343         |
| `dns`                |                  | +31_959    | 10.20 K              | 47_112         |
| `erc1155`            |                  | +46_413    | 27.50 K              | 94_224         |
| `erc20`              |                  | +37_098    | 9.80 K               | 47_112         |
| `erc721`             |                  | +90_930    | 13.70 K              | 125_632        |
| `flipper`            |                  | +15_357    | 1.76 K               | 15_704         |
| `incrementer`        |                  | +15_364    | 1.64 K               | 15_704         |
| `multisig`           |                  | +46_824    | 26.79 K              | 103_580        |
| `proxy`              |                  | +29_614    | 3.81 K               | 32_243         |
| `rand-extension`     |                  | +9_050     | 5.12 K               | 15_704         |
| `subber`             |                  |            | 2.96 K               |                |
| `trait-erc20`        |                  | +36_453    | 10.10 K              | 47_112         |
| `trait-flipper`      |                  | +15_362    | 1.53 K               | 15_704         |
| `trait-incrementer`  |                  | +30_728    | 1.62 K               | 31_408         |



[Link to the run](https://gitlab.parity.io/parity/ink-waterfall/-/pipelines/178358) | Last update: Tue Feb  8 21:14:16 CET 2022

**Comment by HCastano** [comment]
Closing since this will be made obsolete with #1217. Thanks for the PR though!

**Pull request closed without merging**
