### PR TITLE
Make logo visible in GitHub App

### PR DESCRIPTION
**Pull request by cmichi**
The GitHub App uses a dark theme, in which the transparent ink! logo is barely visible.

I added a white background and some padding to the logo. It barely changes the layout when viewed via the GitHub website, but makes the logo visible in the app.

The GitHub website background is pure white, so making the background of the logo white also didn't change anything to how the logo appears when viewed on the GitHub website.

[Preview here](https://github.com/paritytech/ink/tree/cmichi-make-logo-ready-for-dark-mode)

## Before vs. After

<div style="float:left;">

</div>
<div style="float:left;">

</div>

### CODE REVIEW

**Comment by Robbepop** [comment]
While I like this improvement we should do something else with our logo. Maybe paint it pink/purple or add some white glow around it that looks better than a white box.

**Comment by goldsteinsveta** [comment]
Hey @Robbepop and @cmichi

ink_logo_glow_onDark
ink_logo_border_onDark

I played around with the "glow" idea which I think has potential in itself but because it doesn't look like anything else Parity (it's still Parity ink!, isn't it?) and I feel like it's a bit too mysterious for Squink not to be scared around it 🙈. I'd just go with something simple for now. Here's an image file:

ink!_logo 1

**Comment by Robbepop** [comment]
> Hey @Robbepop and @cmichi
> 
> ink_logo_glow_onDark
> ink_logo_border_onDark
> 
> I played around with the "glow" idea which I think has potential in itself but because it doesn't look like anything else Parity (it's still Parity ink!, isn't it?) and I feel like it's a bit too mysterious for Squink not to be scared around it see_no_evil. I'd just go with something simple for now. Here's an image file:
> 
> ink!_logo 1

I absolutely love the glowing version! :heart_eyes:

**Comment by cmichi** [comment]
@goldsteinsveta Thanks a lot! ❤️

**Comment by Robbepop** [comment]
We will merge this today using the mysterious glowing version but leave the underlying issue open for further future improvements.

**Review by Robbepop — APPROVED** [review]

**Pull request merged**
