### PR TITLE
ERC-721 example: fix panic re: `approve_for` with nonexistent token

### PR DESCRIPTION
**Pull request by zgrannan**
## Summary

- [n] y/n | Does it introduce breaking changes?
- [n] y/n | Is it dependant on the specific version of `cargo-contract` or `pallet-contracts`?

In the current ERC-721 example used in integration tests (which is the source of the erc-721 example in ink-examples), the `approve_for` function will panic with the text '"Error with AccountId"' if the token id does not exist. This PR changes the function to return an `Error::TokenNotFound` in this case instead.

I am using [Prusti](https://www.pm.inf.ethz.ch/research/prusti.html) to verify correctness properties of the contract; the presence of this bug prevents the verification of a "panic-freedom" property. 

## Description

Updated the logic and added a corresponding test.

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have added an entry to `CHANGELOG.md`
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules **No dependent changes**

### CODE REVIEW

**Review by ascjones — APPROVED** [review]
LGTM

**Comment by ascjones** [comment]
Need to run `cargo fmt` to fix CI

**Review by ascjones — COMMENTED** [review]
There are a couple of other instances of calling `self.owner_of` which panic when `None`, could you fix those here too?

**Comment by zgrannan** [comment]
@ascjones done

**Review by ascjones — APPROVED** [review]

**Pull request merged**
