### PR TITLE
Add JSON schema for metadata

### PR DESCRIPTION
**Pull request by HCastano**
This PR introduces a [JSON schema](https://json-schema.org/) which describes the contract
metadata. There are two schemas, the outer metadata (generated by `cargo-contract`) and
the versioned ink! metadata.

(This distinction only exists because `cargo-contract` is technically agnostic to the
language metadata, although in practice it's really only using the ink! metadata. In the
future we should be able to merge these into a single schema.)

The schemas provide a source of truth about what key-value pairs are supported and what
types they expect. This is useful for developers as well as external tooling. One use
case here is tooling which needs to verify that a given piece of metadata is valid.

Note that the generated process for the schemas is currently using some hacked branches
across `scale-info`, `ink`, and `cargo-contract` (the generation process is described in
the metadata crate's `README`). My goal is that in the future we'll be able to properly
upstream these changes across our repos and have an easy way to generate the schemas from
`cargo-contract`. At that point we'll be able to get rid of these hardcoded schema files.

Related issue: #940

### CODE REVIEW

**Review by cmichi — APPROVED** [review]
For some whatever reason I cannot add suggestions to the readme. I'm approving it hence now and might create a follow-up PR. 

For the `Metadata Schema Generation`, do you plan on upstreaming those changes?

**Comment by HCastano** [comment]
> For the Metadata Schema Generation, do you plan on upstreaming those changes?

Yeah. I think the ideal workflow would be to have an option in `cargo-contract` to generate the schema. Will take a bit to upstream though since it cuts through a few repos

**Review by ascjones — APPROVED** [review]
LGTM

**Comment by HCastano** [comment]
CI failures are unrelated to this PR

**Pull request merged**
