### PR TITLE
Update to subxt v0.3

### PR DESCRIPTION
**Pull request by ascjones**
Supersedes #273

### CODE REVIEW

**Comment by jsulmont** [comment]
the contract build and generate-metadata failure is the same problem i was having

**Comment by ascjones** [comment]
@jsulmont yeah that's weird - I'm looking at it now

**Comment by jsulmont** [comment]
> @jsulmont yeah that's weird - I'm looking at it now



> @jsulmont yeah that's weird - I'm looking at it now

https://matrix.to/#/!tYUCYdSvSYPMjWNDDD:matrix.parity.io/$1574671770807227Qbnvb:matrix.org?via=matrix.parity.io&via=matrix.org&via=web3.foundation

**Comment by Robbepop** [comment]
> > @jsulmont yeah that's weird - I'm looking at it now
> 
> Somehow, the CI should install the new cargo binary by running cargo install --force cargo-contract --path . from cloned https://github.com/jsulmont/ink/tree/jan_update_subxt
> I just can't find where this is set up

@TriplEight

**Comment by TriplEight** [comment]
Rebuilding CI docker image. It reinstalls `cargo-contract` from master.

**Comment by Robbepop** [comment]
I ll merge even though CI doesn't pass so that Denis can more easily update the associated dockerfile and expect follow-ups in case of breakage.

**Comment by jsulmont** [comment]
> > > @jsulmont yeah that's weird - I'm looking at it now
> > 
> > 
> > Somehow, the CI should install the new cargo binary by running cargo install --force cargo-contract --path . from cloned https://github.com/jsulmont/ink/tree/jan_update_subxt
> > I just can't find where this is set up
> 
> @TriplEight

So my commit was right (besides no nowrap()) ...

**Comment by Robbepop** [comment]
> > > > @jsulmont yeah that's weird - I'm looking at it now
> > > 
> > > 
> > > Somehow, the CI should install the new cargo binary by running cargo install --force cargo-contract --path . from cloned https://github.com/jsulmont/ink/tree/jan_update_subxt
> > > I just can't find where this is set up
> > 
> > 
> > @TriplEight
> 
> So my commit was right (besides no nowrap()) ...

Yes and due to this confusion we are going to change the CI that this no longer happens in the future.

**Pull request merged**
