### PR TITLE
Replacing `cargo test` with `cargo nextest` - Part 2

### PR DESCRIPTION
**Pull request by lean-apple**
Additional tests to conclude if we should use `cargo nextest` instead of `cargo test` 

Related to https://github.com/paritytech/ink/pull/1514. 

3rd tasks of https://github.com/paritytech/ink/issues/1474

### CODE REVIEW

**Comment by lean-apple** [comment]
Time Comparison btw `cargo test` and `cargo nextest` coming from this [job](https://gitlab.parity.io/parity/mirrors/ink/-/pipelines/247781)

| Step - Substep / Tool      | `test` | `nextest`   |
| :---        |    :----:   |          ---: |
| clippy-std - dylint      | 2 min 19       |  2 min 39     |
| workspace - test      | 6 min 43       |  - --    | 
| workspace - codecov      | 8 min 15       |  7 min 54     |
| examples - test      | 19 min 46       |  20 min 40     |

still not really concluant about the benefits of `cargo nextest`

**Comment by ascjones** [comment]
So the conclusion is it doesn't really speed things up, and in some cases is marginally slower?

**Comment by lean-apple** [comment]
I think we reached this same conclusion ... 
The point is for `substrate` or `cumulus` as @alvicsam apparently told me there is a significant difference, 
But because the times for these stages are not really 'high' the difference is not significative, 
Do you think @alvicsam working on [this](https://github.com/paritytech/ink/issues/1520) could improve the use of `cargo nextest` ?

**Comment by cmichi** [comment]
@lean-apple If you mark your PR as draft it can't be merged by accident.

**Comment by cmichi** [comment]
I'm closing this PR and the issue as the results are inconclusive, we might revisit after https://github.com/paritytech/ink/issues/1520.

**Comment by xermicus** [comment]
Since the main thing (regarding performance) of `nextest` is it's improved concurrent execution model, performance gains probably highly depend on the test runner? I'd expect multi-core machines to see significant gains (otherwise should investigate as to why not), but single-core GHA potato-runners probably won't benefit much.

**Comment by alvicsam** [comment]
It seems that for tests in `ink!` repo there is not going to be huge improvement with nextest. There was 3 jobs with nextest in this PR: `examples-nextest`, `codecov-nextest` and `dylint-nextest`. For all of them the longest part was to build the binary.
 - In [dylint-test](https://gitlab.parity.io/parity/mirrors/ink/-/jobs/2423228) there was only one test so it's no much difference between `cargo-test` and `cargo-nextest`.
 - In [codecov-nextest](https://gitlab.parity.io/parity/mirrors/ink/-/jobs/2423236) I see a lot of tests that are super fast (0.01s-0.05s). IMO for these tests there is also no much difference between `cargo-test` and `cargo-nextest`.
 - In [examples-nextest](https://gitlab.parity.io/parity/mirrors/ink/-/jobs/2423238) I see a lot of tests but they are also quick especially if we compare with the time of building the binary.

I see the only way to make the pipeline faster: divide `examples-test` into several jobs

**Pull request closed without merging**
