### PR TITLE
Added example dijkstra algorithm

### PR DESCRIPTION
**Pull request by Irene-123**
Hello, I was working on learning smart contracts and developed Dijkstra's Algorithm in rust which computes the shortest path between 2 nodes. I'm wondering if this is a good implementation of rust and could be added as an example for people to learn. I believe it could be very helpful for students and beginners to learn and get their hands on Rust! Thank you

### CODE REVIEW

**Comment by HCastano** [comment]
Hey @Irene-123! As @SkymanOne mentioned in #1571, this isn't an ink! specific example. Any examples that are part of this repository assume that readers already know Rust.

If you're looking to get feedback on your Rust, or share your Rust knowledge with others, you should check out [Exercism](https://exercism.org/tracks/rust).

**Comment by Irene-123** [comment]
Thank you

**Comment by ascjones** [comment]
I haven't looked at the code but it sounds like this is not the type of computation one would want to do on-chain in a smart contract. Please continue to experiment with `ink!` though and share your examples with us though.

**Comment by Irene-123** [comment]
Sure definitely I would try more realistic examples!

**Pull request closed without merging**
