### PR TITLE
Not generate metadata if compile_as_dependency is true

### PR DESCRIPTION
**Pull request by xgreenx**
Extracted change from this PR:
https://github.com/paritytech/ink/pull/810

### CODE REVIEW

**Comment by Robbepop** [comment]
CI is apparently not happy with this. I don't yet know why but it might not be related to this PR in particular.

**Comment by xgreenx** [comment]
> CI is apparently not happy with this. I don't yet know why but it might not be related to this PR in particular.

CI in master fails. This PR must fix that: https://github.com/paritytech/ink/pull/812

**Comment by Robbepop** [comment]
> > CI is apparently not happy with this. I don't yet know why but it might not be related to this PR in particular.
> 
> CI in master fails. This PR must fix that: #812

merged that one. please rebase.

**Review by Robbepop — APPROVED** [review]

**Review by Robbepop — APPROVED** [review]
I want to point out that this PR just unifies what we are already doing elsewhere.

**Pull request merged**
