### PR TITLE
Change CI variables source to Vault

### PR DESCRIPTION
**Pull request by sergejparity**
Change behavior of the CI pipeline to use Vault secrets instead of project variables.

### CODE REVIEW

**Comment by HCastano** [comment]
@sergejparity can you explain to a non-Devops person what this change is about? What are Vault secrets, and why are they better than the current approach?

**Comment by TriplEight** [comment]
@HCastano [this](https://github.com/paritytech/ci_cd/wiki/Handling-CI-CD-secrets-with-Hashicorp-Vault) wiki page should answer your questions. Don't hesitate to ask more and we will update it.

**Comment by HCastano** [comment]
@sergejparity can you fix the secret provider issue with the `ink-waterfall` pipeline?

**Comment by TriplEight** [comment]
interesting! This probably means that we'll have to at least add the prevoder definition
```
  variables:
    VAULT_SERVER_URL:              "https://vault.parity-mgmt-vault.parity.io"
    VAULT_AUTH_PATH:               "gitlab-parity-io-jwt"
    VAULT_AUTH_ROLE:               "cicd_gitlab_parity_${CI_PROJECT_NAME}"
```
to https://github.com/paritytech/ink-waterfall/blob/master/.gitlab-ci.yml

**Review by TriplEight — CHANGES_REQUESTED** [review]
- please first fix the issue with `ink-waterfall`
- I think it's better to mention the needed secrets in every job rather than import them everywhere

**Comment by sergejparity** [comment]
> interesting! This probably means that we'll have to at least add the prevoder definition
> 
> ```
>   variables:
>     VAULT_SERVER_URL:              "https://vault.parity-mgmt-vault.parity.io"
>     VAULT_AUTH_PATH:               "gitlab-parity-io-jwt"
>     VAULT_AUTH_ROLE:               "cicd_gitlab_parity_${CI_PROJECT_NAME}"
> ```
> 
> to https://github.com/paritytech/ink-waterfall/blob/master/.gitlab-ci.yml.
> Even though that project doesn't seem to use the secrets.

Yes, very strange. Looks like we have here classic example of violation of software development principle - "loose coupling, high cohesion". Will investigate it.

**Comment by TriplEight** [comment]
Did you try adding these variables directly to the waterfall CI config?

Another thing with it is that GItLab requires elevated permissions from those who are triggering the downstream pipelines' protected branches, please make sure you have the right to do so, or change the mirroring in waterfall project's UI to allow maintainers to merge into the master or other protected branch.

**Comment by sergejparity** [comment]
Found an issue with pipeline. `variables:` block can be defined just ones per job as multiple definition lead to collision, the latest defined will cancel previous ones. And this was resolved by moving Vault access variables out of the anchor to main pipeline `variables:` block. Leaving only `secrets:` defined inside anchor `.vault-secrets`. Now it correctly starting `ink-waterfall` job.
Also cleaned up history.

**Review by TriplEight — APPROVED** [review]

**Pull request merged**
