### PR TITLE
`[ink_e2e]` upgrade requirement for `contract-build` to `2.0.2`

### LINKED ISSUE #1692: E2E fails to compile when running in a separate file
1. create a separate file `e2e_tests.rs` and move all the code from `e2e_tests` module there (without `mod e2e_tests`)
2. add these lines on top of e2e_tests.rs file:
```rust
use crate::flipper::*;

#[cfg(all(test, feature = "e2e-tests"))]
pub use ink_e2e::build_message;
```
3 .in lib.rs add this:
```rust
#[cfg(all(test, feature = "e2e-tests"))]
pub mod e2e_tests;
```

It may run for the first time, but when rust-analyzer analyzes the project and expands macros, it messes up built artefacts.
When trying to run `cargo test --features e2e-tests` after rust-analyzer analysis:
```sh
   Compiling flipper v4.0.1 (/Users/skyman/Projects/ink-examples/flipper)
 [1/*] Building cargo project
    Finished release [optimized] target(s) in 0.13s
error: custom attribute panicked
 --> e2e_tests.rs:8:1
  |
8 | #[ink_e2e::test]
  | ^^^^^^^^^^^^^^^^
  |
  = help: message: Metadata artifacts not generated
```

### PR DESCRIPTION
**Pull request by ascjones**
Fixes #1692 and https://github.com/paritytech/ink/issues/1677.

### CODE REVIEW

**Review by SkymanOne — APPROVED** [review]
Thanks!

**Comment by blairmunroakusa** [comment]
Hi! This issue has been affecting my work (per [#1692](https://github.com/paritytech/ink/issues/1692) and [#1677](https://github.com/paritytech/ink/issues/1677)). How do I go about applying this fix to my work? I do not quite understand what I should do on my end to get this working.

**Comment by SkymanOne** [comment]
> Hi! This issue has been affecting my work (per [#1692](https://github.com/paritytech/ink/issues/1692) and [#1677](https://github.com/paritytech/ink/issues/1677)). How do I go about applying this fix to my work? I do not quite understand what I should do on my end to get this working.

You can either wait for next patch release of ink! or you can point your ink! dependencies to git master branch (in case you need this fix now). With the latter option, I'd still recommend change it back to the next ink! crate release once its out.

**Comment by ascjones** [comment]
Because it's a patch release you should be able to just `cargo update -p contract-build` in your contract dir which should pull in the latest version. You can confirm with `cargo tree -p contract-build`.

**Comment by blairmunroakusa** [comment]
@SkymanOne @ascjones Thank you!

**Pull request merged**
