### PR TITLE
DAO example

### PR DESCRIPTION
**Pull request by Daanvdplas**
I wrote a very simple DAO implementation, for details see the README.

Commented out `emit_event()` logic which I was not able to get to work, I think it is due to cross contract implementation (https://github.com/paritytech/ink/issues/1000), but it will be good to include it in the future (but let me know and I'll remove it). 

It is more of a simple draft where I can make changes to meet the requirements you guys expect from this example.

Would love to get feedback :) !

### CODE REVIEW

**Review by ascjones — COMMENTED** [review]
We have a new repo https://github.com/paritytech/ink-examples/ for hosting examples. Could you open this PR against that repository instead?

The `integration-tests` here will be restricted to existing examples and testing of specific features for regression tests.

**Comment by ascjones** [comment]
Okay, I didn't know about the policy for adding examples, see https://github.com/paritytech/ink-examples/blob/main/README.md#can-i-add-a-new-example-here

**Comment by Daanvdplas** [comment]
My apologies @ascjones, I don't really understand what there is to look for in the last link you provided?

**Comment by SkymanOne** [comment]
Hey @Daanvdplas Are you still working on this?

**Comment by SkymanOne** [comment]
Closing as it was decided to move it to the https://github.com/paritytech/ink-examples

**Pull request closed without merging**
