### PR TITLE
Fix miri compilation

### PR DESCRIPTION
**Pull request by Robbepop**
Due to the most recent [blog post](https://www.ralfj.de/blog/2020/09/28/miri.html) about (recent) changes in `miri` we think it is a good time to try (again) to integrate it into our CI. Note that this PR does not integrate `miri` into our CI but instead makes the codebase work again with `miri`.
Since we only have to check `ink_core` (lots of `unsafe` code) the command is:
```
cargo miri test --manifest-path crates/core/Cargo.toml
```

What needed to be done:

- Do not test the `ink_core/env` crypto hashes:
    - Reason: `miri` does not (yet) support running inline assembly which those tests make use of.

Current failures:

`bitstash` unit tests are failing with the following error:

```
test result: ok. 278 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

thread panicked while processing panic. aborting.
error: abnormal termination: the evaluated program aborted execution
   --> /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:561:9
    |
561 |         intrinsics::abort()
    |         ^^^^^^^^^^^^^^^^^^^ the evaluated program aborted execution
    |
    = note: inside `std::panicking::rust_panic_with_hook` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:561:9
    = note: inside closure at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:484:9
    = note: inside `std::sys_common::backtrace::__rust_end_short_backtrace::<[closure@std::panicking::begin_panic_handler::{closure#0} 0:&std::fmt::Arguments, 1:&std::panic::PanicInfo, 2:&std::panic::Location], !>` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153:18
    = note: inside `core::panicking::panic_fmt::panic_impl` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:5
    = note: inside `core::panicking::panic_fmt` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:85:14
    = note: inside `std::result::unwrap_failed` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/macros/mod.rs:19:9
    = note: inside `std::result::Result::<std::option::Option<std::boxed::Box<dyn std::io::Write + std::marker::Send>>, std::thread::AccessError>::expect` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933:23
    = note: inside `std::thread::LocalKey::<std::cell::RefCell<std::option::Option<std::boxed::Box<dyn std::io::Write + std::marker::Send>>>>::with::<[closure@std::io::set_panic::{closure#0} 0:std::option::Option<std::boxed::Box<dyn std::io::Write + std::marker::Send>>], std::option::Option<std::boxed::Box<dyn std::io::Write + std::marker::Send>>>` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
    = note: inside `std::io::set_panic` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:893:5
    = note: inside `std::panicking::default_hook` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:221:30
    = note: inside `std::panicking::rust_panic_with_hook` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:577:17
    = note: inside closure at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:484:9
    = note: inside `std::sys_common::backtrace::__rust_end_short_backtrace::<[closure@std::panicking::begin_panic_handler::{closure#0} 0:&std::fmt::Arguments, 1:&std::panic::PanicInfo, 2:&std::panic::Location], !>` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153:18
    = note: inside `core::panicking::panic_fmt::panic_impl` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:5
    = note: inside `core::panicking::panic_fmt` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:85:14
    = note: inside `std::result::unwrap_failed` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/macros/mod.rs:19:9
    = note: inside `std::result::Result::<std::option::Option<std::boxed::Box<dyn std::io::Write + std::marker::Send>>, std::thread::AccessError>::expect` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933:23
    = note: inside `std::thread::LocalKey::<std::cell::RefCell<std::option::Option<std::boxed::Box<dyn std::io::Write + std::marker::Send>>>>::with::<[closure@std::io::set_panic::{closure#0} 0:std::option::Option<std::boxed::Box<dyn std::io::Write + std::marker::Send>>], std::option::Option<std::boxed::Box<dyn std::io::Write + std::marker::Send>>>` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
    = note: inside `std::io::set_panic` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/io/stdio.rs:893:5
    = note: inside `std::panicking::default_hook` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:221:30
    = note: inside `std::panicking::rust_panic_with_hook` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:577:17
    = note: inside closure at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:484:9
    = note: inside `std::sys_common::backtrace::__rust_end_short_backtrace::<[closure@std::panicking::begin_panic_handler::{closure#0} 0:&std::fmt::Arguments, 1:&std::panic::PanicInfo, 2:&std::panic::Location], !>` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:153:18
    = note: inside `core::panicking::panic_fmt::panic_impl` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:483:5
    = note: inside `core::panicking::panic_fmt` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:85:14
    = note: inside `std::result::unwrap_failed` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/macros/mod.rs:19:9
    = note: inside `std::result::Result::<(), std::thread::AccessError>::expect` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933:23
    = note: inside `std::thread::LocalKey::<std::cell::RefCell<env::engine::off_chain::EnvInstance>>::with::<[closure@crates/core/src/env/engine/off_chain/mod.rs:271:23: 271:63 f:[closure@crates/core/src/env/api.rs:241:46: 243:6 key:&&ink_primitives::Key]], ()>` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
note: inside `<env::engine::off_chain::EnvInstance as env::engine::OnInstance>::on_instance::<[closure@crates/core/src/env/api.rs:241:46: 243:6 key:&&ink_primitives::Key], ()>` at crates/core/src/env/engine/off_chain/mod.rs:271:9
   --> crates/core/src/env/engine/off_chain/mod.rs:271:9
    |
271 |         INSTANCE.with(|instance| f(&mut instance.borrow_mut()))
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `env::api::clear_contract_storage` at crates/core/src/env/api.rs:241:5
   --> crates/core/src/env/api.rs:241:5
    |
241 | /     <EnvInstance as OnInstance>::on_instance(|instance| {
242 | |         Env::clear_contract_storage(instance, key)
243 | |     })
    | |______^
note: inside `storage::lazy::lazy_imap::LazyIndexMap::<storage::collections::bitstash::counts::CountFree>::clear_packed_at` at crates/core/src/storage/lazy/lazy_imap.rs:291:13
   --> crates/core/src/storage/lazy/lazy_imap.rs:291:13
    |
291 |             crate::env::clear_contract_storage(&root_key);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `storage::collections::vec::Vec::<storage::collections::bitstash::counts::CountFree>::clear_cells` at crates/core/src/storage/collections/vec/mod.rs:120:13
   --> crates/core/src/storage/collections/vec/mod.rs:120:13
    |
120 |             self.elems.clear_packed_at(index);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `storage::collections::vec::impls::<impl std::ops::Drop for storage::collections::vec::Vec<storage::collections::bitstash::counts::CountFree>>::drop` at crates/core/src/storage/collections/vec/impls.rs:33:9
   --> crates/core/src/storage/collections/vec/impls.rs:33:9
    |
33  |         self.clear_cells();
    |         ^^^^^^^^^^^^^^^^^^
    = note: inside `std::intrinsics::drop_in_place::<storage::collections::vec::Vec<storage::collections::bitstash::counts::CountFree>> - shim(Some(storage::collections::vec::Vec<storage::collections::bitstash::counts::CountFree>))` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
    = note: inside `std::intrinsics::drop_in_place::<storage::collections::bitstash::BitStash> - shim(Some(storage::collections::bitstash::BitStash))` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
    = note: inside `std::intrinsics::drop_in_place::<storage::alloc::allocator::DynamicAllocator> - shim(Some(storage::alloc::allocator::DynamicAllocator))` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
    = note: inside `std::intrinsics::drop_in_place::<storage::alloc::init::DynamicAllocatorState> - shim(Some(storage::alloc::init::DynamicAllocatorState))` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
    = note: inside `std::intrinsics::drop_in_place::<std::cell::UnsafeCell<storage::alloc::init::DynamicAllocatorState>> - shim(Some(std::cell::UnsafeCell<storage::alloc::init::DynamicAllocatorState>))` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
    = note: inside `std::intrinsics::drop_in_place::<std::cell::RefCell<storage::alloc::init::DynamicAllocatorState>> - shim(Some(std::cell::RefCell<storage::alloc::init::DynamicAllocatorState>))` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
    = note: inside `std::intrinsics::drop_in_place::<std::option::Option<std::cell::RefCell<storage::alloc::init::DynamicAllocatorState>>> - shim(Some(std::option::Option<std::cell::RefCell<storage::alloc::init::DynamicAllocatorState>>))` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175:1
    = note: inside `std::mem::drop::<std::option::Option<std::cell::RefCell<storage::alloc::init::DynamicAllocatorState>>>` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:881:24
    = note: inside `std::thread::local::fast::destroy_value::<std::cell::RefCell<storage::alloc::init::DynamicAllocatorState>>` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:519:13
    = note: inside `std::sys_common::thread_local_dtor::register_dtor_fallback::run_dtors` at /home/robrob/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/thread_local_dtor.rs:43:17

error: aborting due to previous error; 2 warnings emitted

error: test failed, to rerun pass '--lib'
```

### CODE REVIEW

**Comment by TriplEight** [comment]
Closes https://github.com/paritytech/devops/issues/541

**Comment by Robbepop** [comment]
I decided that we want to postpone this until `miri` is less of pain to use for us. Closed.

**Comment by TriplEight** [comment]
According to the [doc](https://github.com/rust-lang/miri/#running-miri-on-ci) it should work better now. Up to some fixes?
I'm not sure which of your crates you want to test.

cc: https://github.com/paritytech/ink/pull/401/files  https://github.com/paritytech/ink/pull/496

**Comment by Robbepop** [comment]
The most important crates for `miri` testing are `ink_env` and `ink_storage` as well as `ink_primitives` eventually.

**Comment by TriplEight** [comment]
alright, now there's something to work with @Robbepop

**Comment by Robbepop** [comment]
Outdated PR by now. Needs another attempt in order to introduce miri.

**Pull request closed without merging**
