### PR TITLE
CI: fix coverage

### PR DESCRIPTION
**Pull request by TriplEight**
- restores code coverage how it used to measure previously - with an old-style instrumentation (but with branch coverage)
- some chore

CC: https://github.com/paritytech/ink/pull/857
Closes: paritytech/ci_cd#160 https://github.com/paritytech/ink/pull/863 https://github.com/paritytech/ci_cd/issues/13

### CODE REVIEW

**Comment by TriplEight** [comment]
Note: https://github.com/paritytech/ink/pull/863#pullrequestreview-710866706

**Comment by TriplEight** [comment]
Feel free to merge if you're OK to do without `-Clink-dead-code `.

**Comment by HCastano** [comment]
> Feel free to merge if you're OK to do without `-Clink-dead-code `.

I'm hesitant to merge without this since Robin mentioned that having this flag [was correct](https://github.com/paritytech/ink/pull/863#pullrequestreview-710866706). Does the Codecov job not pass if this flag is enabled, or what happens?

**Comment by TriplEight** [comment]
Shish, I thought it already works for a month. It could have worked at least somehow. The job breaks with this flag.

**Comment by cmichi** [comment]
I'll merge in the current state and create create a follow-up adding the `-Clink-dead-code` flag and a fix for the error it causes.

**Pull request merged**
