### PR TITLE
Update to parity-scale-codec `3` and scale-info `2`

### PR DESCRIPTION
**Pull request by ascjones**
Supersedes #1124

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
## 🦑 📈 ink! Example Contracts ‒ Changes Report 📉 🦑
 These are the results when building the `examples/*` contracts from this branch with `cargo-contract 0.17.0-942c50c` and comparing them to ink! `master`: 

|                      | Δ Optimized Size | Δ Used Gas | Total Optimized Size | Total Used Gas |
|:----------------------|------------------:|------------:|----------------------:|----------------:|
| `accumulator`        | -0.08 K          |            | 1.35 K               |                |
| `adder`              | -0.47 K          |            | 2.47 K               |                |
| `contract-terminate` | -0.08 K          |            | 1.23 K               | 215_704        |
| `contract-transfer`  | -0.08 K          |            | 8.47 K               | 15_704         |
| `delegator`          | -0.77 K          | -510       | 6.86 K               | 50_833         |
| `dns`                | -0.51 K          |            | 9.70 K               | 47_112         |
| `erc1155`            | -0.20 K          |            | 28.12 K              | 94_224         |
| `erc20`              | -0.47 K          |            | 9.34 K               | 47_112         |
| `erc721`             | -0.53 K          |            | 13.17 K              | 125_632        |
| `flipper`            | -0.13 K          |            | 1.63 K               | 15_704         |
| `incrementer`        | -0.08 K          |            | 1.56 K               | 15_704         |
| `multisig`           | -0.52 K          | -658       | 26.25 K              | 102_922        |
| `proxy`              | -0.51 K          | -157       | 3.36 K               | 32_147         |
| `rand-extension`     | -0.48 K          |            | 4.64 K               | 15_704         |
| `subber`             | -0.47 K          |            | 2.48 K               |                |
| `trait-erc20`        | -0.47 K          |            | 9.64 K               | 47_112         |
| `trait-flipper`      | -0.11 K          |            | 1.41 K               | 15_704         |
| `trait-incrementer`  | -0.08 K          |            | 1.54 K               | 31_408         |



[Link to the run](https://gitlab.parity.io/parity/ink-waterfall/-/pipelines/179247) | Last update: Tue Feb 15 12:01:01 CET 2022

**Comment by athei** [comment]
Still strange that gas doesn't change for all contracts where the site changed. Is the size change maybe in a path that isn't hit by the waterfall?

**Review by athei — APPROVED** [review]
Nice

**Review by cmichi — APPROVED** [review]
> Still strange that gas doesn't change for all contracts where the size changed. Is the size change maybe in a path that isn't hit by the waterfall?

I also find it strange, I can create a follow-up issue in the waterfall to look into it.

**Pull request merged**
