### PR TITLE
Replace array impls with const generics

### LINKED ISSUE #752: Use `min_const_generics` for trait implementations
We should make use of `min_const_generics` for our trait implementation here:
https://github.com/paritytech/ink/blob/master/crates/storage/src/traits/impls/arrays.rs

### PR DESCRIPTION
**Pull request by austinabell**
Closes #752 

Not sure if you would like it under a feature to not be a breaking change (if msrv is important), but happy to make that change if so :D

### CODE REVIEW

**Comment by Robbepop** [comment]
Thank you for the PR @austinabell !

> Not sure if you would like it under a feature to not be a breaking change (if msrv is important), but happy to make that change if so :D

We won't need to feature flag this since we are on Rust nightly which includes (by definition) the latest Rust 1.51 where this feature has already been stabilized.

**Comment by Robbepop** [comment]
The CI is currently unhappy due to examples needing to be updated with the updated SCALE codec crate. However, I'd instead love to see support for this in SCALE codec crate prior to merging this PR. Would be cool if you want to spearhead this!

**Comment by austinabell** [comment]
> The CI is currently unhappy due to examples needing to be updated with the updated SCALE codec crate. However, I'd instead love to see support for this in SCALE codec crate prior to merging this PR. Would be cool if you want to spearhead this!

Ah my bad, I thought this was assumed, I should have put that comment in the description. Yeah I'm leaving this PR in draft state until https://github.com/paritytech/parity-scale-codec/pull/261 comes in, then I'll update the reference here and open up the PR.

I was just too lazy to patch all examples since it was a temporary check to make sure everything compiles.

**Review by Robbepop — APPROVED** [review]
LGTM

Requires update to `cargo-contract` template.

**Comment by austinabell** [comment]
> LGTM
> 
> Requires update to `cargo-contract` template.

That change is merged :) Anything else needed?

**Review by ascjones — APPROVED** [review]

**Comment by Robbepop** [comment]
> 
> 
> > LGTM
> > Requires update to `cargo-contract` template.
> 
> That change is merged :) Anything else needed?

Does look like it to me tbh https://github.com/paritytech/cargo-contract/blob/master/templates/new/_Cargo.toml#L14

**Comment by austinabell** [comment]
> > > LGTM
> > > Requires update to `cargo-contract` template.
> > 
> > 
> > That change is merged :) Anything else needed?
> 
> Does not look like it to me tbh https://github.com/paritytech/cargo-contract/blob/master/templates/new/_Cargo.toml#L14

oh ooops lol, the different naming threw me off there. That's a dumb mistake, I'll update that now

**Comment by Robbepop** [comment]
Thanks a lot for your PR @austinabell ! :)

**Pull request merged**
